-- ============================================================
-- CADD Tech HRMS — Announcements Table
-- Run this in the Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  category text not null default 'Company',
  author text not null,
  author_empid text not null,
  date date not null default CURRENT_DATE,
  pinned boolean not null default false,
  created_at timestamptz default now()
);

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- Everyone authenticated can view announcements
CREATE POLICY "Anyone can view announcements"
  ON public.announcements FOR SELECT
  USING ( true );

-- Only HR can insert announcements
CREATE POLICY "HR can insert announcements"
  ON public.announcements FOR INSERT
  WITH CHECK ( public.is_hr() );

-- Only HR can update announcements
CREATE POLICY "HR can update announcements"
  ON public.announcements FOR UPDATE
  USING ( public.is_hr() );

-- Only HR can delete announcements
CREATE POLICY "HR can delete announcements"
  ON public.announcements FOR DELETE
  USING ( public.is_hr() );
