-- ============================================================
-- CADD Tech HRMS — Leave Requests Table
-- Run this in the Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS public.leave_requests (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  type text not null check (type in ('Casual', 'Sick', 'Earned', 'Unpaid')),
  from_date date not null,
  to_date date not null,
  days integer not null,
  reason text default '',
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  reviewer_note text default '',
  reviewed_by text default '',
  applied_on date not null default CURRENT_DATE,
  created_at timestamptz default now()
);

ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;

-- Employees can view their own leave requests
DROP POLICY IF EXISTS "Employees view own leaves" ON public.leave_requests;
CREATE POLICY "Employees view own leaves"
  ON public.leave_requests FOR SELECT
  TO authenticated
  USING ( employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid()) );

-- HR can view all leave requests
DROP POLICY IF EXISTS "HR view all leaves" ON public.leave_requests;
CREATE POLICY "HR view all leaves"
  ON public.leave_requests FOR SELECT
  TO authenticated
  USING ( public.is_hr() );

-- Employees can insert their own leave requests
DROP POLICY IF EXISTS "Employees insert own leaves" ON public.leave_requests;
CREATE POLICY "Employees insert own leaves"
  ON public.leave_requests FOR INSERT
  TO authenticated
  WITH CHECK (
    employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid())
    AND status = 'Pending'
  );

-- HR can update leave requests (approve/reject)
DROP POLICY IF EXISTS "HR update leaves" ON public.leave_requests;
CREATE POLICY "HR update leaves"
  ON public.leave_requests FOR UPDATE
  TO authenticated
  USING ( public.is_hr() );
