-- ============================================================
-- DEPRECATED — see setup/travel_allowance_schema.sql
-- ============================================================
-- The travel allowance feature was renamed from "onboarding".
-- The table is now public.travel_allowance_requests.
--
-- Run setup/travel_allowance_schema.sql (it migrates the old
-- onboarding_requests table and adds the new tables/columns).
-- Do NOT run this file.
-- ============================================================
