-- ============================================================
-- CADD Tech HRMS — Onboarding Requests Table
-- Run this in the Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS public.onboarding_requests (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  request_date date not null default CURRENT_DATE,
  from_location text not null,
  destination text not null,
  travel_cost numeric(12,2) default 0,
  purpose text not null,
  additional_details text default '',
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  reviewer_note text default '',
  reviewed_by text default '',
  reviewed_at timestamptz,
  created_at timestamptz default now()
);

ALTER TABLE public.onboarding_requests ENABLE ROW LEVEL SECURITY;

-- Employees can view their own onboarding requests
CREATE POLICY "Employees view own onboarding"
  ON public.onboarding_requests FOR SELECT
  USING ( employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid()) );

-- HR can view all onboarding requests
CREATE POLICY "HR view all onboarding"
  ON public.onboarding_requests FOR SELECT
  USING ( public.is_hr() );

-- Employees can insert their own onboarding requests
CREATE POLICY "Employees insert own onboarding"
  ON public.onboarding_requests FOR INSERT
  WITH CHECK (
    employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid())
    AND status = 'Pending'
  );

-- Employees can update their own pending onboarding requests
CREATE POLICY "Employees update own pending onboarding"
  ON public.onboarding_requests FOR UPDATE
  USING (
    employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid())
    AND status = 'Pending'
  );

-- HR can update onboarding requests (approve/reject)
CREATE POLICY "HR update onboarding"
  ON public.onboarding_requests FOR UPDATE
  USING ( public.is_hr() );
