-- ============================================================
-- CADD Tech HRMS — Permission Requests + HR Notifications
-- Run this in the Supabase SQL Editor (safe to re-run).
-- ============================================================

-- Each employee may take up to 3 permission hours per month.
-- A permission request records a single date with a from/to time;
-- the duration is stored in minutes and is auto-computed by the app.
CREATE TABLE IF NOT EXISTS public.permission_requests (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  date date not null,
  from_time time not null,
  to_time time not null,
  duration_minutes integer not null,
  reason text default '',
  status text not null default 'Approved' check (status in ('Approved', 'Rejected', 'Cancelled')),
  created_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS idx_permission_requests_emp_date
  ON public.permission_requests (employee_id, date);

ALTER TABLE public.permission_requests ENABLE ROW LEVEL SECURITY;

-- Employees can view their own permission requests
CREATE POLICY "Employees view own permissions"
  ON public.permission_requests FOR SELECT
  USING ( employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid()) );

-- HR can view all permission requests
CREATE POLICY "HR view all permissions"
  ON public.permission_requests FOR SELECT
  USING ( public.is_hr() );

-- Employees can insert their own permission requests (status fixed to 'Approved')
CREATE POLICY "Employees insert own permissions"
  ON public.permission_requests FOR INSERT
  WITH CHECK (
    employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid())
    AND status = 'Approved'
  );

-- HR can update permission requests (e.g. reject/cancel)
CREATE POLICY "HR update permissions"
  ON public.permission_requests FOR UPDATE
  USING ( public.is_hr() );

-- In-app notifications surfaced to HR (currently audience = 'hr').
CREATE TABLE IF NOT EXISTS public.hr_notifications (
  id bigint generated by default as identity primary key,
  audience text not null default 'hr',
  title text not null,
  body text default '',
  link text default '',
  read boolean not null default false,
  created_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS idx_hr_notifications_created
  ON public.hr_notifications (created_at DESC);

ALTER TABLE public.hr_notifications ENABLE ROW LEVEL SECURITY;

-- Only HR can read notifications
CREATE POLICY "HR view notifications"
  ON public.hr_notifications FOR SELECT
  USING ( public.is_hr() );

-- Any authenticated user (the requesting employee) may create a notification
CREATE POLICY "Authenticated users insert notifications"
  ON public.hr_notifications FOR INSERT
  WITH CHECK ( auth.uid() IS NOT NULL );

-- HR can mark notifications as read
CREATE POLICY "HR update notifications"
  ON public.hr_notifications FOR UPDATE
  USING ( public.is_hr() );
