-- ============================================================
-- CADD Tech HRMS — Permission Requests + HR Notifications
-- Run this in the Supabase SQL Editor (safe to re-run).
-- ============================================================

-- Each employee may take up to 3 permission hours per month.
-- A permission request records a single date with a from/to time;
-- the duration is stored in minutes and is auto-computed by the app.
CREATE TABLE IF NOT EXISTS public.permission_requests (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  date date not null,
  from_time time not null,
  to_time time not null,
  duration_minutes integer not null,
  reason text default '',
  status text not null default 'Approved' check (status in ('Approved', 'Rejected', 'Cancelled')),
  created_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS idx_permission_requests_emp_date
  ON public.permission_requests (employee_id, date);

ALTER TABLE public.permission_requests ENABLE ROW LEVEL SECURITY;

-- Employees can view their own permission requests
DROP POLICY IF EXISTS "Employees view own permissions" ON public.permission_requests;
CREATE POLICY "Employees view own permissions"
  ON public.permission_requests FOR SELECT
  TO authenticated
  USING ( employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid()) );

-- HR can view all permission requests
DROP POLICY IF EXISTS "HR view all permissions" ON public.permission_requests;
CREATE POLICY "HR view all permissions"
  ON public.permission_requests FOR SELECT
  TO authenticated
  USING ( public.is_hr() );

-- Employees can insert their own permission requests (status fixed to 'Approved')
DROP POLICY IF EXISTS "Employees insert own permissions" ON public.permission_requests;
CREATE POLICY "Employees insert own permissions"
  ON public.permission_requests FOR INSERT
  TO authenticated
  WITH CHECK (
    employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid())
    AND status = 'Approved'
  );

-- HR can update permission requests (e.g. reject/cancel)
DROP POLICY IF EXISTS "HR update permissions" ON public.permission_requests;
CREATE POLICY "HR update permissions"
  ON public.permission_requests FOR UPDATE
  TO authenticated
  USING ( public.is_hr() );

-- In-app notifications surfaced to HR (currently audience = 'hr').
CREATE TABLE IF NOT EXISTS public.hr_notifications (
  id bigint generated by default as identity primary key,
  audience text not null default 'hr',
  title text not null,
  body text default '',
  link text default '',
  read boolean not null default false,
  created_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS idx_hr_notifications_created
  ON public.hr_notifications (created_at DESC);

ALTER TABLE public.hr_notifications ENABLE ROW LEVEL SECURITY;

-- Only HR can read notifications
DROP POLICY IF EXISTS "HR view notifications" ON public.hr_notifications;
CREATE POLICY "HR view notifications"
  ON public.hr_notifications FOR SELECT
  TO authenticated
  USING ( public.is_hr() );

-- Any authenticated user (the requesting employee) may create a notification
DROP POLICY IF EXISTS "Authenticated users insert notifications" ON public.hr_notifications;
CREATE POLICY "Authenticated users insert notifications"
  ON public.hr_notifications FOR INSERT
  TO authenticated
  WITH CHECK ( public.app_current_empid() IS NOT NULL AND audience = 'hr' );

-- HR can mark notifications as read
DROP POLICY IF EXISTS "HR update notifications" ON public.hr_notifications;
CREATE POLICY "HR update notifications"
  ON public.hr_notifications FOR UPDATE
  TO authenticated
  USING ( public.is_hr() );

CREATE SCHEMA IF NOT EXISTS hrms_private;
REVOKE ALL ON SCHEMA hrms_private FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA hrms_private TO authenticated;

CREATE TABLE IF NOT EXISTS hrms_private.permission_quota_locks (
  employee_month text PRIMARY KEY,
  revision boolean NOT NULL DEFAULT false
);
ALTER TABLE hrms_private.permission_quota_locks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE hrms_private.permission_quota_locks FROM PUBLIC, anon, authenticated;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_constraint
    WHERE conrelid = 'public.permission_requests'::regclass AND conname = 'permission_duration_valid') THEN
    ALTER TABLE public.permission_requests ADD CONSTRAINT permission_duration_valid CHECK (
      duration_minutes > 0 AND duration_minutes <= 180 AND to_time > from_time
      AND duration_minutes = extract(epoch FROM (to_time - from_time)) / 60
    ) NOT VALID;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION hrms_private.enforce_permission_quota()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  new_month date := date_trunc('month', NEW.date)::date;
  new_lock text := NEW.employee_id || ':' || new_month::text;
  old_lock text;
  used_minutes bigint;
BEGIN
  IF auth.uid() IS NULL OR (NOT public.is_hr() AND NEW.employee_id IS DISTINCT FROM public.app_current_empid()) THEN
    RAISE EXCEPTION 'Not authorized' USING ERRCODE = '42501';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE empid = NEW.employee_id) THEN
    RAISE EXCEPTION 'Employee profile missing' USING ERRCODE = '23503';
  END IF;
  IF TG_OP = 'UPDATE' THEN
    old_lock := OLD.employee_id || ':' || date_trunc('month', OLD.date)::date::text;
  END IF;
  IF old_lock IS NOT NULL AND old_lock <> new_lock THEN
    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(least(old_lock, new_lock), 0));
    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(greatest(old_lock, new_lock), 0));
  ELSE
    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(new_lock, 0));
  END IF;
  IF old_lock IS NOT NULL AND old_lock <> new_lock THEN
    INSERT INTO hrms_private.permission_quota_locks (employee_month) VALUES (old_lock)
    ON CONFLICT (employee_month) DO UPDATE
      SET revision = NOT hrms_private.permission_quota_locks.revision;
  END IF;
  INSERT INTO hrms_private.permission_quota_locks (employee_month) VALUES (new_lock)
  ON CONFLICT (employee_month) DO UPDATE
    SET revision = NOT hrms_private.permission_quota_locks.revision;
  IF NEW.status <> 'Rejected' THEN
    SELECT COALESCE(sum(duration_minutes), 0) INTO used_minutes
    FROM public.permission_requests
    WHERE employee_id = NEW.employee_id AND date >= new_month
      AND date < (new_month + interval '1 month')::date
      AND status <> 'Rejected' AND id IS DISTINCT FROM NEW.id;
    IF used_minutes + NEW.duration_minutes > 180 THEN
      RAISE EXCEPTION 'Monthly permission limit is 180 minutes' USING ERRCODE = '23514';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION hrms_private.enforce_permission_quota() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS enforce_permission_quota ON public.permission_requests;
CREATE TRIGGER enforce_permission_quota BEFORE INSERT OR UPDATE ON public.permission_requests
FOR EACH ROW EXECUTE FUNCTION hrms_private.enforce_permission_quota();
