-- ============================================================
-- CADD Tech HRMS — Seed Data & Schema Setup
-- Run this in the Supabase SQL Editor
-- ============================================================

-- 1. Create profiles table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid references auth.users on delete cascade primary key,
  empid text unique not null,
  name text not null,
  role text not null check (role in ('hr', 'employee')),
  department text not null,
  created_at timestamptz default now()
);

-- Turn on RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create a Security Definer function to check if the current user is HR without triggering RLS recursion
CREATE OR REPLACE FUNCTION public.is_hr()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'hr'
  );
$$;

-- Profiles Policies
-- HR can read all profiles
CREATE POLICY "HR can view all profiles"
  ON public.profiles
  FOR SELECT
  USING ( public.is_hr() );

-- Employees can read their own profile
CREATE POLICY "Employees can view own profile"
  ON public.profiles
  FOR SELECT
  USING (auth.uid() = id);

-- Users can insert their own profile (used during signup)
CREATE POLICY "Users can insert own profile"
  ON public.profiles
  FOR INSERT
  WITH CHECK (auth.uid() = id);

-- HR can delete profiles
CREATE POLICY "HR can delete profiles"
  ON public.profiles
  FOR DELETE
  USING ( public.is_hr() );

-- HR can insert profiles (for adding new employees)
CREATE POLICY "HR can insert profiles"
  ON public.profiles
  FOR INSERT
  WITH CHECK ( public.is_hr() );

-- 2. Mock Tables for Attendance (Assuming they don't exist yet for this demo setup)
CREATE TABLE IF NOT EXISTS public.emp_attendance (
  id bigint generated by default as identity primary key,
  empid text not null,
  name text,
  checkin time,
  checkout time,
  work_ot numeric,
  date date not null
);

ALTER TABLE public.emp_attendance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "HR can view all attendance"
  ON public.emp_attendance FOR SELECT
  USING ( public.is_hr() );

CREATE POLICY "Employee can view own attendance"
  ON public.emp_attendance FOR SELECT
  USING (
    empid = (SELECT empid FROM public.profiles WHERE id = auth.uid())
  );

-- Monthly Attendance Table
CREATE TABLE IF NOT EXISTS public.emp_monthly (
  id bigint generated by default as identity primary key,
  empid text not null,
  name text,
  checkin time,
  checkout time,
  work_ot numeric,
  date date not null
);

ALTER TABLE public.emp_monthly ENABLE ROW LEVEL SECURITY;

CREATE POLICY "HR can view all monthly"
  ON public.emp_monthly FOR SELECT
  USING ( public.is_hr() );

CREATE POLICY "Employee can view own monthly"
  ON public.emp_monthly FOR SELECT
  USING (
    empid = (SELECT empid FROM public.profiles WHERE id = auth.uid())
  );

-- ==========================================
-- 3. Seed Test Users
-- IMPORTANT: This script uses raw auth inserts for demo purposes.
-- It is strongly recommended to use the Supabase JS client or API to create users in production, 
-- as it hashes passwords properly.
-- The below raw inserts into auth.users require cryptographic hashing for the password, 
-- which can't easily be done in raw SQL here.
--
-- INSTEAD: 
-- Please run the following JavaScript in your browser console on the login page 
-- to create the test users safely using the Supabase client:
--
-- await supabase.auth.signUp({ email: '0001@caddtech.local', password: 'AdminPassword123' })
-- await supabase.auth.signUp({ email: '0002@caddtech.local', password: 'EmpPassword123' })
--
-- Then, run this SQL to link their profiles (replace the UUIDs):

/*
INSERT INTO public.profiles (id, empid, name, role, department)
VALUES
  ('<UUID_FOR_0001>', '0001', 'Aarav Mehta', 'hr', 'Training'),
  ('<UUID_FOR_0002>', '0002', 'Ravi Kumar', 'employee', 'Civil');
*/


