CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  empid text UNIQUE NOT NULL,
  name text NOT NULL,
  role text NOT NULL CHECK (role IN ('hr', 'employee')),
  department text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE SCHEMA IF NOT EXISTS hrms_private;
REVOKE ALL ON SCHEMA hrms_private FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA hrms_private TO authenticated;

CREATE OR REPLACE FUNCTION hrms_private.is_hr()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT auth.uid() IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'hr'
  );
$$;
REVOKE ALL ON FUNCTION hrms_private.is_hr() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION hrms_private.is_hr() TO authenticated;

CREATE OR REPLACE FUNCTION public.is_hr()
RETURNS boolean
LANGUAGE sql STABLE SECURITY INVOKER
SET search_path = ''
AS $$ SELECT hrms_private.is_hr(); $$;
REVOKE ALL ON FUNCTION public.is_hr() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_hr() TO authenticated;

CREATE OR REPLACE FUNCTION hrms_private.current_empid()
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT empid FROM public.profiles
  WHERE auth.uid() IS NOT NULL AND id = auth.uid();
$$;
REVOKE ALL ON FUNCTION hrms_private.current_empid() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION hrms_private.current_empid() TO authenticated;

CREATE OR REPLACE FUNCTION public.app_current_empid()
RETURNS text
LANGUAGE sql STABLE SECURITY INVOKER
SET search_path = ''
AS $$ SELECT hrms_private.current_empid(); $$;
REVOKE ALL ON FUNCTION public.app_current_empid() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.app_current_empid() TO authenticated;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.profiles FROM PUBLIC, anon;
GRANT SELECT, INSERT, DELETE ON TABLE public.profiles TO authenticated;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
DROP POLICY IF EXISTS "HR can view all profiles" ON public.profiles;
DROP POLICY IF EXISTS "Employees can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Anyone authenticated can view all profiles" ON public.profiles;
CREATE POLICY "Anyone authenticated can view all profiles" ON public.profiles
  FOR SELECT TO authenticated USING (public.app_current_empid() IS NOT NULL);
DROP POLICY IF EXISTS "HR can insert profiles" ON public.profiles;
CREATE POLICY "HR can insert profiles" ON public.profiles
  FOR INSERT TO authenticated WITH CHECK (public.is_hr());
DROP POLICY IF EXISTS "HR can delete profiles" ON public.profiles;
CREATE POLICY "HR can delete profiles" ON public.profiles
  FOR DELETE TO authenticated USING (public.is_hr());

CREATE TABLE IF NOT EXISTS public.emp_attendance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empid text NOT NULL, name text, checkin time, checkout time,
  work_ot numeric, date date NOT NULL
);
CREATE TABLE IF NOT EXISTS public.emp_monthly (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empid text NOT NULL, name text, checkin time, checkout time,
  work_ot numeric, date date NOT NULL
);
ALTER TABLE public.emp_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emp_monthly ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.emp_attendance, public.emp_monthly FROM PUBLIC, anon;
GRANT SELECT ON TABLE public.emp_attendance, public.emp_monthly TO authenticated;
DROP POLICY IF EXISTS "HR can view all attendance" ON public.emp_attendance;
CREATE POLICY "HR can view all attendance" ON public.emp_attendance
  FOR SELECT TO authenticated USING (public.is_hr());
DROP POLICY IF EXISTS "Employee can view own attendance" ON public.emp_attendance;
CREATE POLICY "Employee can view own attendance" ON public.emp_attendance
  FOR SELECT TO authenticated USING (empid = public.app_current_empid());
DROP POLICY IF EXISTS "HR can view all monthly" ON public.emp_monthly;
CREATE POLICY "HR can view all monthly" ON public.emp_monthly
  FOR SELECT TO authenticated USING (public.is_hr());
DROP POLICY IF EXISTS "Employee can view own monthly" ON public.emp_monthly;
CREATE POLICY "Employee can view own monthly" ON public.emp_monthly
  FOR SELECT TO authenticated USING (empid = public.app_current_empid());
