-- ============================================================
-- CADD Tech HRMS — Travel Allowance Schema (Migration)
-- Run this ONCE in the Supabase SQL Editor.
--
-- Covers Task 5 changes:
--   1. Rename onboarding_requests -> travel_allowance_requests
--   2. Add travel_distance_km column
--   3. Create perf_targets (HR-set performance targets)
--   4. Create employee_details (with branch, dept, location, etc.)
--
-- NOTE: app_meta (used for the reimbursement rate + monthly perf
-- reset) is created by setup/performance_reset.sql. Keep that table.
-- ============================================================

-- ---------- 1. Travel Allowance Requests ----------
-- Rename the old onboarding table if it still exists (preserves data)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'onboarding_requests'
  ) THEN
    ALTER TABLE public.onboarding_requests RENAME TO travel_allowance_requests;
  END IF;
END $$;

-- Create fresh if it does not exist yet (first-time setup)
CREATE TABLE IF NOT EXISTS public.travel_allowance_requests (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  request_date date not null default CURRENT_DATE,
  from_location text not null,
  destination text not null,
  travel_distance_km numeric(12,2) default 0,
  travel_cost numeric(12,2) default 0,
  purpose text not null,
  additional_details text default '',
  status text not null default 'Pending'
    check (status in ('Pending', 'Approved', 'Rejected')),
  reviewer_note text default '',
  reviewed_by text default '',
  reviewed_at timestamptz,
  created_at timestamptz default now()
);

-- Ensure the distance column exists (covers the rename case)
ALTER TABLE public.travel_allowance_requests
  ADD COLUMN IF NOT EXISTS travel_distance_km numeric(12,2) default 0;

-- ---------- Row Level Security ----------
ALTER TABLE public.travel_allowance_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Employees view own onboarding" ON public.travel_allowance_requests;
DROP POLICY IF EXISTS "HR view all onboarding" ON public.travel_allowance_requests;
DROP POLICY IF EXISTS "Employees insert own onboarding" ON public.travel_allowance_requests;
DROP POLICY IF EXISTS "Employees update own pending onboarding" ON public.travel_allowance_requests;
DROP POLICY IF EXISTS "HR update onboarding" ON public.travel_allowance_requests;

CREATE POLICY "Employees view own travel allowance"
  ON public.travel_allowance_requests FOR SELECT
  USING ( employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid()) );

CREATE POLICY "HR view all travel allowance"
  ON public.travel_allowance_requests FOR SELECT
  USING ( public.is_hr() );

CREATE POLICY "Employees insert own travel allowance"
  ON public.travel_allowance_requests FOR INSERT
  WITH CHECK (
    employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid())
    AND status = 'Pending'
  );

CREATE POLICY "Employees update own pending travel allowance"
  ON public.travel_allowance_requests FOR UPDATE
  USING (
    employee_id = (SELECT empid FROM public.profiles WHERE id = auth.uid())
    AND status = 'Pending'
  );

CREATE POLICY "HR update travel allowance"
  ON public.travel_allowance_requests FOR UPDATE
  USING ( public.is_hr() );

-- ---------- 2. Performance Targets ----------
CREATE TABLE IF NOT EXISTS public.perf_targets (
  attr_key text primary key,
  target numeric not null default 0
);

-- ---------- 3. Employee Details ----------
CREATE TABLE IF NOT EXISTS public.employee_details (
  empid text primary key,
  designation text default '',
  description text default '',
  email text default '',
  phone text default '',
  department text default '',
  branch text default '',
  location text default '',
  join_date date,
  employment_type text default 'Full-time'
);

ALTER TABLE public.employee_details ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Employees view own details" ON public.employee_details;
CREATE POLICY "Employees view own details"
  ON public.employee_details FOR SELECT
  USING ( empid = (SELECT empid FROM public.profiles WHERE id = auth.uid()) );

DROP POLICY IF EXISTS "HR view all details" ON public.employee_details;
CREATE POLICY "HR view all details"
  ON public.employee_details FOR SELECT
  USING ( public.is_hr() );

DROP POLICY IF EXISTS "Employees upsert own details" ON public.employee_details;
CREATE POLICY "Employees upsert own details"
  ON public.employee_details FOR INSERT
  WITH CHECK ( empid = (SELECT empid FROM public.profiles WHERE id = auth.uid()) );

DROP POLICY IF EXISTS "Employees update own details" ON public.employee_details;
CREATE POLICY "Employees update own details"
  ON public.employee_details FOR UPDATE
  USING ( empid = (SELECT empid FROM public.profiles WHERE id = auth.uid()) );

DROP POLICY IF EXISTS "HR upsert details" ON public.employee_details;
CREATE POLICY "HR upsert details"
  ON public.employee_details FOR INSERT
  WITH CHECK ( public.is_hr() );

DROP POLICY IF EXISTS "HR update details" ON public.employee_details;
CREATE POLICY "HR update details"
  ON public.employee_details FOR UPDATE
  USING ( public.is_hr() );
