-- ============================================================
-- CADD Tech HRMS — Work From Home (WFH) Requests
-- Run this ONCE in the Supabase SQL Editor.
--
-- A separate table from scraped attendance (emp_attendance /
-- emp_monthly / emp_last6months) and from leave_requests.
-- Approved WFH requests override the scraped attendance status
-- (including "Absent") via the shared resolution service in the app.
--
-- Reuses the already-deployed helper public.app_current_empid()
-- (from setup/travel_allowance_schema.sql) and public.is_hr()
-- (from setup/seed-users.sql). Safe to re-run.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.wfh_requests (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  from_date date not null,
  to_date date not null,
  reason text default '',
  status text not null default 'Pending'
    check (status in ('Pending', 'Approved', 'Rejected')),
  reviewer_note text default '',
  reviewed_by text default '',
  applied_on date not null default CURRENT_DATE,
  created_at timestamptz default now()
);

ALTER TABLE public.wfh_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Employees view own wfh" ON public.wfh_requests;
CREATE POLICY "Employees view own wfh"
  ON public.wfh_requests FOR SELECT
  USING ( employee_id = public.app_current_empid() );

DROP POLICY IF EXISTS "HR view all wfh" ON public.wfh_requests;
CREATE POLICY "HR view all wfh"
  ON public.wfh_requests FOR SELECT
  USING ( public.is_hr() );

DROP POLICY IF EXISTS "Employees insert own wfh" ON public.wfh_requests;
CREATE POLICY "Employees insert own wfh"
  ON public.wfh_requests FOR INSERT
  WITH CHECK (
    employee_id = COALESCE(public.app_current_empid(), employee_id)
    AND employee_id IS NOT NULL
    AND status = 'Pending'
  );

DROP POLICY IF EXISTS "HR update wfh" ON public.wfh_requests;
CREATE POLICY "HR update wfh"
  ON public.wfh_requests FOR UPDATE
  USING ( public.is_hr() );
